### ISSUE TITLE
关于网站访问速度优化

### ISSUE THREAD

**Issue by caojiele** [Soptq/Soptq.github.io#11]
想问下你的网站访问速度做了哪些优化，感觉你的页面打开挺快的。

**Comment by Soptq** [comment]
代码层面的话主要是：
1. 图片懒加载
2. DNS prefetch
3. 让渲染页面内容，框架的代码提前。减少白屏的时间
4. 页面 preload
5. 压缩图片之内的比较大的文件
6. js 和 css 尽量都通过 cdn 引入，因为 github 的 cdn 在天朝时快时慢

目前就想到这些，如果还有想到的再补充。

**Comment by caojiele** [comment]
Hi,
你这边用到了哪些？


--
Best Regards！
Jiele


原始邮件
发件人:Soptqnotifications@github.com
收件人:Soptq/Soptq.github.ioSoptq.github.io@noreply.github.com
抄送:天璇caojiele1225@126.com; Authorauthor@noreply.github.com
发送时间:2019年7月24日(周三) 20:25
主题:Re: [Soptq/Soptq.github.io] 关于网站访问速度优化 (#11)


代码层面的话主要是：
图片懒加载 DNS prefetch 让渲染页面内容，框架的代码提前。减少白屏的时间 页面 preload 压缩图片之内的比较大的文件 js 和 css 尽量都通过 cdn 引入，因为 github 的 cdn 在天朝时快时慢
目前就想到这些，如果还有想到的再补充。

**Comment by Soptq** [comment]
我上面提到的都用到了😂，如果想要最省事的话可以去买一个cdn服务，我要是域名可以备案的话可能就直接买cdn了也不做这些优化了。

**Comment by caojiele** [comment]
是的，但是网站如果没有备份到国内的服务器上，域名是不能备案的，所以还要买个服务器。😂发自我的iPhone------------------ 原始邮件 ------------------发件人: Soptq  <notifications@github.com>发送时间: 2019年7月26日 01:04收件人: Soptq/Soptq.github.io <Soptq.github.io@noreply.github.com>抄送: 天璇 <caojiele1225@126.com>, Author <author@noreply.github.com>主题: 回复：[Soptq/Soptq.github.io] 关于网站访问速度优化 (#11)我上面提到的都用到了😂，如果想要最省事的话可以去买一个cdn服务，我要是域名可以备案的话可能就直接买cdn了也不做这些优化了。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Soptq/Soptq.github.io/issues/11?email_source=notifications\u0026email_token=AHEMYTXIYVZ2M4A5ZYD7NLTQBHMLBA5CNFSM4IGLYVC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD22DL2I#issuecomment-515126761",
"url": "https://github.com/Soptq/Soptq.github.io/issues/11?email_source=notifications\u0026email_token=AHEMYTXIYVZ2M4A5ZYD7NLTQBHMLBA5CNFSM4IGLYVC2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD22DL2I#issuecomment-515126761",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
