### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by caojiele** [Soptq/Soptq.github.io#2]
Hi, Soptq.
              I saw your add these effect, really good.But I hope I can in the heart of the instructions how to realize the function description, convenient we study better. Good luck with you.

**Comment by Soptq** [comment]
Thank you. I am currently working on a project at school. When I'm done, I will write an introduction to the features implemented by this blog. And make them configurable as well.

**Comment by caojiele** [comment]
> Thank you. I am currently working on a project at school. When I'm done, I will write an introduction to the features implemented by this blog. And make them configurable as well.

Ok, let us together look forward to it.
