### ISSUE TITLE
如何发布文章？

### ISSUE THREAD

**Issue by yiyu-liao** [Soptq/Soptq.github.io#28]
你好，首先感谢开源～～ 作品非常棒，我这边按照文档delete了文件夹下的数据，怎样发布自己的文章呢？ 我在_post添加了，在网站刷新没有看到文章

**Comment by Soptq** [comment]
请问现在解决了吗？如果没有解决的话，可以把你的项目代码给我看一下吗，我刚刚查看了你的仓库发现你的 yiyu-liao.github.io 仓库里面是空的。因为刷新没有看到文章可能会有很多方面的问题，我直接看一下代码应该会快一些。谢谢支持！

**Comment by yiyu-liao** [comment]
现在问题解决啦，是因为我的文章的命名不对导致的，本地能够成功跑起来了，谢谢～

还有，想请问下，header nav是在哪里配置的呢，我只想要HOME, ABOUT, ARCHIVE这三个tag

Soptq <notifications@github.com> 于2019年12月23日周一 下午2:48写道：

**Comment by Soptq** [comment]
header nav 是自动配置的，比如你不想要playground这个tag，你就把目录下面的playground文件夹删掉就可以了
